import type { Flight } from './types';

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: 1,
    airline: 'ایران ایر',
    logo: '🛫',
    flightNumber: 'IR-301',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '08:00',
    arrivalTime: '09:30',
    duration: '1 ساعت و 30 دقیقه',
    price: 2500000,
    availableSeats: 45,
    stops: 0,
    class: 'economy',
    features: ['وای‌فای رایگان', 'غذا', 'بیمه مسافرتی'],
  },
  {
    id: 2,
    airline: 'ماهان',
    logo: '✈️',
    flightNumber: 'W5-1024',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '10:30',
    arrivalTime: '12:00',
    duration: '1 ساعت و 30 دقیقه',
    price: 2800000,
    availableSeats: 32,
    stops: 0,
    class: 'economy',
    features: ['وای‌فای رایگان', 'غذا', 'سرگرمی'],
  },
  {
    id: 3,
    airline: 'آسمان',
    logo: '🛩️',
    flightNumber: 'EP-752',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '14:00',
    arrivalTime: '15:30',
    duration: '1 ساعت و 30 دقیقه',
    price: 2600000,
    availableSeats: 28,
    stops: 1,
    class: 'economy',
    features: ['غذا', 'بیمه مسافرتی'],
  },
  {
    id: 4,
    airline: 'قشم ایر',
    logo: '🛫',
    flightNumber: 'QB-1142',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '16:30',
    arrivalTime: '18:00',
    duration: '1 ساعت و 30 دقیقه',
    price: 2400000,
    availableSeats: 52,
    stops: 0,
    class: 'economy',
    features: ['غذا'],
  },
  {
    id: 5,
    airline: 'ایران ایر',
    logo: '🛫',
    flightNumber: 'IR-305',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '19:00',
    arrivalTime: '20:30',
    duration: '1 ساعت و 30 دقیقه',
    price: 2700000,
    availableSeats: 18,
    stops: 1,
    class: 'economy',
    features: ['وای‌فای رایگان', 'غذا', 'بیمه مسافرتی', 'سرگرمی'],
  },
];

export const MOCK_BUSES = [
  {
    id: 1,
    company: 'اتوبوسرانی تهران',
    logo: '🚌',
    tripNumber: 'TB-401',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '07:30',
    arrivalTime: '16:00',
    duration: '۸ ساعت و ۳۰ دقیقه',
    price: 450000,
    availableSeats: 28,
    features: ['صندلی VIP', 'تهویه', 'پذیرایی'],
  },
  {
    id: 2,
    company: 'همسفر',
    logo: '🚍',
    tripNumber: 'HM-220',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '14:00',
    arrivalTime: '22:30',
    duration: '۸ ساعت و ۳۰ دقیقه',
    price: 380000,
    availableSeats: 15,
    features: ['Wi-Fi', 'شارژر'],
  },
  {
    id: 3,
    company: 'گیتی‌پیما',
    logo: '🚌',
    tripNumber: 'GP-118',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '21:00',
    arrivalTime: '05:30',
    duration: '۸ ساعت و ۳۰ دقیقه',
    price: 520000,
    availableSeats: 8,
    features: ['تخت‌خواب', 'پذیرایی', 'Wi-Fi'],
  },
];

export const MOCK_TRAINS = [
  {
    id: 1,
    company: 'رجا',
    logo: '🚆',
    tripNumber: 'RJ-301',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '08:00',
    arrivalTime: '18:30',
    duration: '۱۰ ساعت و ۳۰ دقیقه',
    price: 890000,
    availableSeats: 42,
    features: ['کوپه ۴ نفره', 'تهویه', 'رستوران'],
  },
  {
    id: 2,
    company: 'رجا',
    logo: '🚆',
    tripNumber: 'RJ-405',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '15:30',
    arrivalTime: '02:00',
    duration: '۱۰ ساعت و ۳۰ دقیقه',
    price: 750000,
    availableSeats: 18,
    features: ['سالنی', 'تهویه'],
  },
  {
    id: 3,
    company: 'فدک',
    logo: '🚄',
    tripNumber: 'FD-102',
    origin: 'تهران',
    destination: 'مشهد',
    departureTime: '19:00',
    arrivalTime: '05:30',
    duration: '۱۰ ساعت و ۳۰ دقیقه',
    price: 1200000,
    availableSeats: 6,
    features: ['کوپه درجه یک', 'صبحانه', 'Wi-Fi'],
  },
];

export const MOCK_TRIPS = [
  {
    id: 'TR-1001',
    from: 'تهران',
    to: 'مشهد',
    date: '۱۴۰۳/۰۹/۱۵',
    status: 'confirmed' as const,
    airline: 'ایران ایر',
    price: 2500000,
  },
  {
    id: 'TR-1002',
    from: 'شیراز',
    to: 'تهران',
    date: '۱۴۰۳/۱۰/۰۲',
    status: 'pending' as const,
    airline: 'ماهان',
    price: 1800000,
  },
];
